### ISSUE TITLE
Incorrect cursor rendering in visual mode on blank line.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#154]
Repro:
- Move cursor to blank line with no text on it (not even white space).
- Press `v`.
- While you have configured a custom line height (try 1.2)
```
  editor:
    fontSize: 11
    invisibles: {}
    lineHeight: 1.2
```

Symptom: The cursor is misaligned with the line height:
See screenshot:
![screen shot 2016-02-10 at 1 00 21 am](https://cloud.githubusercontent.com/assets/977348/12942788/300045be-cf92-11e5-9503-c1b0e28697be.png)
