### ISSUE TITLE
Changing .block-cursor color?

### ISSUE THREAD

**Issue by jeff-kilbride** [t9md/atom-vim-mode-plus#297]
Hi,

I am using the standard Atom Dark UI Theme with the Darkula syntax theme. The problem is the block cursor in normal (non-insert) mode is too dark and blends into the background. I'm not sure if this is a problem with the syntax theme not defining `@syntax-cursor-color` correctly or something else. The insert mode cursor is fine. I am able to work around this by making the following changes in `vim-mode-plus.less`:
```
// Cursor style
// =========================
.block-cursor(@visibility: visible) {
  border: 0;
  // background-color: @syntax-cursor-color;
  background-color: white;
  visibility: @visibility;
  opacity: 0.6;
}

.underline-cursor(@visibility: visible) {
  border: none;
  // border-bottom: .3em solid @syntax-cursor-color;
  border-bottom: .3em solid white;
  background: none;
  visibility: @visibility;
  opacity: 0.6;
}

.low-block-cursor(@visibility: visible) {
  border: none;
  // border-bottom: .6em solid @syntax-cursor-color;
  border-bottom: .6em solid white;
  background: none;
  visibility: @visibility;
  opacity: 0.6;
}
```
However, this just feels like the wrong way to do it -- and I'm not sure I really need to mess with the `.underline-cursor` and `.low-block-cursor` settings. I tried putting this block in my own `styles.less` file, along with an `@import "ui-variables";` statement, but that didn't work. I also tried defining `@syntax-cursor-color: white;` in my `styles.less` file. That didn't work either. Finally, I would also like to make the block cursor blink, if possible. I'm pretty sure I have to set the `.blink-off` class, but not sure where.

Is there a better / easier way to accomplish this? I want to avoid my changes being overwritten each time there is an upgrade for `vim-mode-plus`. Any help is appreciated! Thanks!

**Comment by clessg** [comment]
I just enable this style whenever I'm using a theme like that:

```css
atom-text-editor.vim-mode-plus.normal-mode::shadow .cursor {
  background: #fff !important;
}
```

**Comment by jeff-kilbride** [comment]
Yep. That worked! Thanks, @clessg.

Any tips for making the cursor blink?

**Comment by clessg** [comment]
This works for me:

```less
atom-text-editor.vim-mode-plus.normal-mode::shadow .cursors.blink-off .cursor {
  visibility: hidden !important;
}
```

Or, if you prefer:

```less
atom-text-editor.vim-mode-plus.normal-mode::shadow {
  .cursor {
    background: #fff !important;
  }
  .cursors.blink-off .cursor {
    visibility: hidden !important;
  }
}
```
