### ISSUE TITLE
cleanup cursor-placement for operator

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#713]
[experiment]

What I'm trying to achieve this PR essentially is
- [Current]: selection prop is saved and used only in visual-mode
- [With this PR]: save selection prop in all operator involved operation
  - Use that info to place cursor( stay and non-stay )
    - if stay, cursor is placed at head of saved selection prop
    - if not stay, cursor is placed at start of saved selection prop
      - This is start of selection in most case.

# Memo

Currently there is still lots of duplicate code in cursor placement on operator.
This PR aiming to consolidate/remove duplicate code for that.

- Basic point info to save
  - Selection start, end, head(= cursor position ), tail

- Roles
  - cursor
  - selection( almost equivalent to cursor )
  - selection property( independently keep **normalized** cursor position for each selection )

- Selection states in operation lifecycle
  - Operation start( `will-select` ): original cursor positions
  - Target selected( `did-select` ): selection range change
  - Occurrence selected( `did-select-occurrence` ): selection range change
  - Target( = selected range ) mutated: in most case selection get emptied
  - Operation finished

**Comment by lacostenycoder** [comment]
Any chance to add a simple way for user to  customize the cursor colors when using this package?  I had to  hack a bit to get a decent result but still can't correctly hack "replace" mode.  Should I open separate issue as feature request?  Here's what I put in my styles.less 

```css
@cursor-color: rgb(230, 11, 168);

.editor .cursor {
  border-left-width: 4px;
  background-color: fade(@cursor-color, 40%);
  border: none;
}

atom-text-editor.vim-mode-plus.normal-mode,
atom-text-editor.vim-mode-plus.visual-mode,
{
    &.is-focused {
      .cursor{
        background-color: fade(@cursor-color, 70%);
        border: none;
    }
  }
}

atom-text-editor.vim-mode-plus.insert-mode.replace,
{
  &.is-focused {
    .cursor {
      background-color: fade(@cursor-color, 20%);
      visibility: visible;
    }
    .cursors.blink-off .cursor {
      background-color: fade(@cursor-color, 20%);
      visibility: visible;
    }
  }
}
```
I apologize for this lame gif.  Was too lazy to crop / edit etc.
![grabb](https://cloud.githubusercontent.com/assets/6077905/25069155/11508882-2247-11e7-8f4b-4aaa100c0e97.gif)
