### ISSUE TITLE
Request feature to easily modify color theme of vim mode cursors

### ISSUE THREAD

**Issue by lacostenycoder** [t9md/atom-vim-mode-plus#757]
- Atom version: 1.15.0
- vim-mode-plus version: 0.89.0 
    - vim-mode-plus-ex-mode 0.9.0
    - vim-mode-plus-key-maps-for-surround: 0.2.1
- MacOS 10.11.6
- You disabled vim-mode?  Yes.
- Tried to latest stable atom version with latest vim-mode-plus: On it.

Request a simple way for user to  customize the cursor.  I hacked a bit to get a decent result but still can't correctly hack "replace" mode.   Here's an example of what I do currently.

```css
@cursor-color: rgb(230, 11, 168);

.editor .cursor {
  border-left-width: 4px;
  background-color: fade(@cursor-color, 40%);
  border: none;
}

atom-text-editor.vim-mode-plus.normal-mode,
atom-text-editor.vim-mode-plus.visual-mode,
{
    &.is-focused {
      .cursor{
        background-color: fade(@cursor-color, 70%);
        border: none;
    }
  }
}

atom-text-editor.vim-mode-plus.insert-mode.replace,
{
  &.is-focused {
    .cursor {
      background-color: fade(@cursor-color, 20%);
      visibility: visible;
    }
    .cursors.blink-off .cursor {
      background-color: fade(@cursor-color, 20%);
      visibility: visible;
    }
  }
}
```
![grabbfast](https://cloud.githubusercontent.com/assets/6077905/25069251/bb5ad150-2249-11e7-9a98-30004f117916.gif)
