### ISSUE TITLE
enhancement request: disable linter while in insert mode

### ISSUE THREAD

**Issue by mattsawyer77** [t9md/atom-vim-mode-plus#795]
It would be nice to disable Atom's linter (or at least the overlays) while in insert mode, since it can get a bit noisy. I can workaround this with CSS as follows:
``` less
atom-text-editor.vim-mode-plus.insert-mode #linter-tooltip {
    display: none;
}
```
but this is somewhat hacky/brittle. I understand if you think this is beyond the scope of vim-mode-plus.
